import type { Post } from './types'

// Fallback posts baked into the bundle so the Writing section is never empty.
// At runtime, useFeed() fetches the live feed.json (generated by
// scripts/build_feed.py at build time) and replaces these when available.
export const fallbackPosts: Post[] = [
  {
    date: 'May 2026',
    title: "Pew Said I'm the Last Millennial. Then They Stopped Counting.",
    dek: "The real split was never 1996. It's the 119-to-1 wealth gap inside my own generation.",
    tag: 'Data Journalism',
    url: 'https://medium.com/@grateful_aqua_goat_147/pew-said-im-the-last-millennial-then-they-stopped-counting-f7308d37197b',
  },
  {
    date: 'May 2026',
    title: "I'm Deaf and Autistic. My Social Life Happens on the Mat.",
    dek: 'I kept tabs on my social energy for 56 days, and the mat came out on top by 4 points.',
    tag: 'Mental Health',
    url: 'https://medium.com/@grateful_aqua_goat_147/im-deaf-and-autistic-my-social-life-happens-on-the-mat-6701f93c3227',
  },
  {
    date: 'Apr 2026',
    title: 'The Traits That Win Power Are the Traits That Destroy It',
    dek: "92 studies. One finding the self-help industry won't touch.",
    tag: 'Psychology',
    url: 'https://medium.com/@grateful_aqua_goat_147/the-traits-that-win-power-are-the-traits-that-destroy-it-2b94802c3896',
  },
  {
    date: 'Mar 2026',
    title: '38,000 to 1',
    dek: 'Medium says letting AI train on your writing protects your reach. For every reader the crawlers send back, they scrape thousands of your pages first.',
    tag: 'Tech Criticism',
    read: '4 min',
    url: 'https://medium.com/@grateful_aqua_goat_147/38-000-to-1-75442ec443ab',
  },
  {
    date: 'Jan 2026',
    title: "You're Probably 5 Bad Days Away From Becoming a Monster",
    dek: "65% of people would do it. The research says you're not in the other 35%.",
    tag: 'Psychology',
    url: 'https://medium.com/@grateful_aqua_goat_147/youre-probably-5-bad-days-away-from-becoming-a-monster-4f8c997e5bf3',
  },
  {
    date: 'Dec 2025',
    title: '33 Years Asleep. 0.1 Seconds to Judge.',
    dek: 'What I found when I stopped guessing at humans and started counting.',
    tag: 'Personal · Data',
    url: 'https://medium.com/@grateful_aqua_goat_147/33-years-asleep-0-1-seconds-to-judge-8a616a15ce3a',
  },
]
